name: 'team_4c2_airbnb_transformations'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  team_4c2_airbnb_transformations:
    staging:
      materialized: view
      snowflake_warehouse: DBT_WAREHOUSE
    marts:
      materialized: table
      snowflake_warehouse: pc_dbt_wh_large